### ISSUE TITLE
Including bin directory and client_secrets.json

### ISSUE THREAD

**Issue by hanxue** [googleplus/gplus-quickstart-java#12]
Hello @gguuss , thank you very much for sharing this straightforward example of Java Google+ authentication. 

I notice in the instructions the developer will have to 

1. Create the `bin` directory
2. Rename or copy `client_secrets.json.example` to `client_secrets.json`

In the spirit to make it simpler, why not create an empty `bin` directory, and simply name the client_secrets file as client_secrets.json ? Should be obvious enough for the developer to see `YOUR_CLIENT_ID` and `YOUR_CLIENT_SECRET` and replace it with the appropriate values.

**Comment by gguuss** [comment]
Thanks for the suggestion!  We left the bin folder and client_secrets.json file out to prevent accidentally checking in credentials or proprietary binaries so for now, leaving as-is.
